# Generated by Django 6.1.1 on 2026-09-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField()),
                ('phone', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('amenities', models.CharField(blank=True, max_length=500)),
                ('available_rooms', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=2)),
            ],
        ),
    ]
